DROP TABLE IF EXISTS TIER_CALCULATION;

CREATE TABLE TIER_CALCULATION
(
    ID      SERIAL PRIMARY KEY,
    UUID    UUID      NOT NULL,
    CRN     VARCHAR   NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    DATA    JSONB NULL
);

CREATE
INDEX TIER_CALCULATION_CRN_CREATED_ON on TIER_CALCULATION(CRN,CREATED);
CREATE
INDEX TIER_CALCULATION_UUID on TIER_CALCULATION(CRN,UUID);