version: "3"
services:
  postgres:
    image: postgres:11
    networks:
      - hmpps
    container_name: hmpps-tier-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=root
  localstack:
    image: localstack/localstack:0.12.20
    networks:
      - hmpps
    container_name: hmpps-tier-localstack
    ports:
      - "4566:4566"
      - 8999:8080
    environment:
      - SERVICES=sns,sqs
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-2
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  community-api:
    image: quay.io/hmpps/community-api:latest
    networks:
      - hmpps
    container_name: community-api
    ports:
     - "8091:8080"
    healthcheck:
     test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev,dev-seed
  assessments-api:
    image: quay.io/hmpps/offender-assessments-api:latest
    networks:
      - hmpps
    container_name: assessments-api
    ports:
     - "8092:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - oauth
  oauth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: oauth
    ports:
      - "9090:9090"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/auth/health" ]
    environment:
      - SERVER_PORT=9090
      - SPRING_PROFILES_ACTIVE=dev
networks:
  hmpps:
