
spring:
  jpa:
    show-sql: true

  datasource:
    url: 'jdbc:h2:mem:probation-tiering;INIT=create domain if not exists jsonb as text;MODE=PostgreSQL;'
    username: probation
    password: tiering

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

logging:
  level:
    uk.gov: DEBUG

server:
  shutdown: immediate
