spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/auth/.well-known/jwks.json

oauth:
  endpoint:
    url: http://localhost:9090/auth
  client:
    id: community-api-client
    secret: community-api-client

community:
  endpoint:
    url: http://localhost:8091/secure
assessment:
  endpoint:
    url: http://localhost:8092