spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

hmpps.sqs:
  provider: localstack
  queues:
    hmppsoffenderqueue:
      queueName: hmpps_offender_event_queue
      dlqName: hmpps_offender_event_dlq
      subscribeTopicId: hmppsoffendertopic
      subscribeFilter: '{"eventType":[ "OFFENDER_MANAGEMENT_TIER_CALCULATION_REQUIRED"] }'
      asyncQueueClient: true
  topics:
    hmppscalculationcompletetopic:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}
      asyncClient: true
    hmppsoffendertopic:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}

logging:
  level:
    uk.gov: DEBUG

server:
  shutdown: immediate
