spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/auth/.well-known/jwks.json

oauth:
  endpoint:
    url: http://localhost:9090/auth
  client:
    id: hmpps-tier
    secret: clientsecret

assessment:
  endpoint:
    url: http://localhost:8092

tier-to-delius:
  endpoint:
    url: http://localhost:8099

hmpps.tier:
  endpoint:
    url: http://localhost:8080