spring:

  jpa:
    show-sql: true

  datasource:
    url: 'jdbc:h2:mem:probation-tiering;INIT=create domain if not exists jsonb as text;MODE=PostgreSQL;'
    username: probation
    password: tiering

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub
          jwk-set-uri: https://localhost/auth/.well-known/jwks.json

oauth:
  endpoint:
    url: http://localhost:9090/auth
  client:
    id: my-diary
    secret: clientsecret

community:
  endpoint:
    url: http://localhost:8082
assessment:
  endpoint:
    url: http://localhost:8081

logging:
  level:
    uk.gov: DEBUG

server:
  shutdown: immediate