
offender-events:
  sqs-endpoint: http://localhost:4576
  sqs-queue: http://localhost:4576/queue/Digital-Prison-Services-dev-hmpps_tier_offender_events_queue
  sqs-provider: localstack

hmpps-events:
  topic: arn:aws:sns:eu-west-2:000000000000:hmpps-domain
  sns-endpoint: http://localhost:4575

calculation-complete:
  sqs-endpoint: http://localhost:4576
  sqs-queue: http://localhost:4576/queue/Digital-Prison-Services-dev-hmpps_tier_calculation_complete_queue

aws:
  hmpps-domain:
    access-key: $key
    secret-access-key: secret
    topic-arn: arn
    region: eu-west-2
  offender:
    access-key: key
    secret-access-key: secret
    region: eu-west-2
