offender-events:
  sqs-endpoint-url: http://localhost:4566
  sqs-queue: http://localhost:4566/000000000000/Digital-Prison-Services-dev-hmpps_tier_offender_events_queue
  sqs-provider: localstack

aws:
  access-key-id: key
  secret-access-key: secret
  region: eu-west-2

community:
  endpoint:
    url: http://localhost:8081/secure

assessment:
  endpoint:
    url: http://localhost:8082