spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://localhost/auth/.well-known/jwks.json

oauth:
  endpoint:
    url: localhost/auth

community:
  endpoint:
    url: localhost
assessment:
  endpoint:
    url: localhost