spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

hmpps.sqs:
  provider: localstack
  queues:
    hmppsdomaineventsqueue:
      queueName: hmpps_domain_events_queue
      dlqName: hmpps_domain_events_dlq
      subscribeTopicId: hmppsdomaineventstopic
      subscribeFilter: '{"eventType":[ "breach.end"] }'
      asyncQueueClient: true

  topics:
    hmppscalculationcompletetopic:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}
      asyncClient: true
    hmppsdomaineventstopic:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}

arns:
  endpoint:
    url: http://localhost:8094

hmpps.tier:
  endpoint:
    url: http://localhost:8080

tier-to-delius:
  endpoint:
    url: http://localhost:8093

oauth:
  endpoint:
    url: http://localhost:9090/auth
  client:
    id: client-id
    secret: client-secret

logging:
  level:
    uk.gov: DEBUG

server:
  shutdown: immediate
