offender-events:
  sqs-endpoint-url: http://localhost:4576
  sqs-queue: http://localhost:4576/queue/Digital-Prison-Services-dev-hmpps_tier_offender_events_queue
  sqs-provider: localstack

aws:
  hmpps-domain:
    access-key: $key
    secret-access-key: secret
    topic-arn: arn
    region: eu-west-2
  offender:
    access-key: key
    secret-access-key: secret
    region: eu-west-2
