package uk.gov.justice.digital.hmpps.hmppstier.service.calculation

import uk.gov.justice.digital.hmpps.hmppstier.client.arns.ScoreType
import uk.gov.justice.digital.hmpps.hmppstier.client.arns.ogrs4.AllPredictorDto
import uk.gov.justice.digital.hmpps.hmppstier.client.arns.ogrs4.StaticOrDynamicPredictorDto
import uk.gov.justice.digital.hmpps.hmppstier.domain.DeliusInputs
import uk.gov.justice.digital.hmpps.hmppstier.domain.enums.Tier
import uk.gov.justice.digital.hmpps.hmppstier.domain.enums.Tier.*
import uk.gov.justice.digital.hmpps.hmppstier.service.calculation.CalculationStep.MAPPA_ROSH
import uk.gov.justice.digital.hmpps.hmppstier.service.calculation.CalculationStep.REOFFENDING
import java.math.BigDecimal
import java.math.BigDecimal.ZERO

internal object ProvisionalStatusCalculator {
    fun isProvisional(
        deliusInputs: DeliusInputs,
        riskPredictors: AllPredictorDto,
        stepResults: Map<CalculationStep, Tier?>,
    ) = provisionalBecausePredictorsAreStatic(riskPredictors, stepResults)
        || provisionalBecauseRoshIsMissing(deliusInputs, riskPredictors, stepResults)

    /**
     * Static predictors (either ARP, CSRP, or both) mean that the result is provisional, unless one of the other results generates a tier at least as high as the highest possible ARP/CSRP result.
     * 1. If both ARP and CSRP are static, provisional = Y unless the final result is tier A as a result of RoSH/MAPPA or DC-SRP.
     * 2. If ARP is static and CSRP is dynamic:
     *    * Determine the maximum possible ARP/CSRP tier for the dynamic CSRP by using the first column in table 1.
     *    * Provisional = Y unless the final result is equal to or higher than that maximum possible, as a result of DC-SRP, RoSH, or other factors.
     * 3. If ARP is dynamic and CSRP is static:
     *    * Determine the maximum possible ARP/CSRP tier for the dynamic ARP by using the first row in table 1.
     *    * Provisional = Y unless the final result is equal to or higher than that maximum possible, as a result of DC-SRP, RoSH, or other factors.
     */
    private fun provisionalBecausePredictorsAreStatic(
        riskPredictors: AllPredictorDto,
        stepResults: Map<CalculationStep, Tier?>,
    ) = with(riskPredictors) {
        val arpStatic = allReoffendingPredictor.isStatic()
        val csrpStatic = combinedSeriousReoffendingPredictor.isStatic()
        val tierWithoutArpOrCsrp = stepResults.filter { it.key != REOFFENDING }.mapNotNull { it.value }.maxOrNull() ?: G
        val maxPossibleTierForStaticArp = ReoffendingPredictorTable.calculate(
            arp = MAX_VALUE,
            csrp = combinedSeriousReoffendingPredictor?.score ?: ZERO
        )
        val maxPossibleTierForStaticCsrp = ReoffendingPredictorTable.calculate(
            arp = allReoffendingPredictor?.score ?: ZERO,
            csrp = MAX_VALUE,
        )

        when {
            arpStatic && csrpStatic -> tierWithoutArpOrCsrp < A
            arpStatic -> tierWithoutArpOrCsrp < maxPossibleTierForStaticArp
            csrpStatic -> tierWithoutArpOrCsrp < maxPossibleTierForStaticCsrp
            else -> false
        }
    }

    /**
     * If the RoSH flag is missing, the tier will be marked as provisional, unless a non-provisional tier A can be generated by either of the following conditions:
     * * Both ARP and CSRP are dynamic and generate tier A in table 1
     * * DC-SRP is Very High
     *
     * Non-MAPPA cases with the RoSH flag missing may also be marked as non-provisional if:
     * * Both ARP and CSRP are dynamic and generate tier C or higher in table 1
     * * DC-SRP generates tier C or higher in tables 2a/2b
     * * Tier B is assigned for a lifer within one year of release
     */
    private fun provisionalBecauseRoshIsMissing(
        deliusInputs: DeliusInputs,
        riskPredictors: AllPredictorDto,
        stepResults: Map<CalculationStep, Tier?>,
    ) = with(deliusInputs.registrations) {
        val missingRosh = rosh == null
        val missingMappa = mappaCategory == null
        val tierWithoutRoshOrMappa = stepResults.filter { it.key != MAPPA_ROSH }
            .filterNot { it.key == REOFFENDING && !riskPredictors.hasDynamicArpAndCsrp() }
            .mapNotNull { it.value }.maxOrNull() ?: G
        when {
            missingRosh && !missingMappa -> tierWithoutRoshOrMappa < A
            missingRosh && missingMappa -> tierWithoutRoshOrMappa < C
            else -> false
        }
    }

    private fun StaticOrDynamicPredictorDto?.isStatic() = this?.staticOrDynamic == ScoreType.STATIC
    private fun StaticOrDynamicPredictorDto?.isDynamic() = this?.staticOrDynamic == ScoreType.DYNAMIC
    private fun AllPredictorDto.hasDynamicArpAndCsrp() =
        allReoffendingPredictor.isDynamic() && combinedSeriousReoffendingPredictor.isDynamic()

    private val MAX_VALUE = BigDecimal.valueOf(Long.MAX_VALUE)
}
