apiVersion: batch/v1
kind: CronJob
metadata:
  name: recalculate-tiers
spec:
  schedule: {{ .Values.recalculate.tier.schedule }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: recalculate-tiers
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - 'curl -fsSL -X POST "https://$BASE_URL/calculations?dryRun=$DRY_RUN" --header "Authorization: Bearer $(curl -fsSL --request POST "$AUTH_BASE_URL/oauth/token?grant_type=client_credentials" --user "$CLIENT_ID:$CLIENT_SECRET"  | jq -r .access_token)" --header "Content-Type: application/json"'
              env:
                - name: AUTH_BASE_URL
                  value: {{ index .Values "generic-service" "env" "OAUTH_ENDPOINT_URL" }}
                - name: BASE_URL
                  value: {{ index .Values "generic-service" "ingress" "host" }}
                - name: DRY_RUN
                  value: "{{ index .Values "generic-service" "env" "FULL_RECALC_DRY_RUN" }}"
                - name: CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: hmpps-tier
                      key: OAUTH_CLIENT_ID
                      optional: false
                - name: CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: hmpps-tier
                      key: OAUTH_CLIENT_SECRET
                      optional: false
          restartPolicy: Never