apiVersion: batch/v1
kind: CronJob
metadata:
  name: recalculate-tiers
spec:
  schedule: {{ index .Values "full-recalculation" "schedule" }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: hmpps-tier
          containers:
            - name: recalculate-tiers
              image: "quay.io/hmpps/hmpps-tier:{{ index .Values "generic-service" "image" "tag" }}"
              securityContext:
                capabilities:
                  drop:
                    - ALL
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                seccompProfile:
                  type: RuntimeDefault
              resources:
                requests:
                  memory: "1Gi"
                  cpu: "4"
                limits:
                  memory: "2Gi"
                  cpu: "4"
              env:
                {{- range $secret, $envs := index .Values "generic-service" "namespace_secrets" }}
                  {{- range $key, $val := $envs }}
                - name: {{ $key }}
                  valueFrom:
                    secretKeyRef:
                      key: {{ trimSuffix "?" $val }}
                      name: {{ $secret }}{{ if hasSuffix "?" $val }}
                      optional: true{{ end }}  {{- end }}
                {{- end }}
                {{- range $key, $val := index .Values "generic-service" "env" }}
                - name: {{ $key }}
                  value: "{{ $val }}"
                {{- end }}
                - name: MESSAGING_CONSUMER_ENABLED
                  value: "false"
                - name: FULL-RECALCULATION_ENABLED
                  value: "true"
                - name: FULL-RECALCULATION_DRY-RUN
                  value: "{{ index .Values "full-recalculation" "dry-run" }}"
          restartPolicy: Never