---
generic-service:
  nameOverride: hmpps-tier

  replicaCount: 2

  image:
    repository: quay.io/hmpps/hmpps-tier
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: hmpps-tier-cert
    path: /

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "aws,logstash,stdout"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-tier:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      OAUTH_CLIENT_ID: "OAUTH_CLIENT_ID"
      OAUTH_CLIENT_SECRET: "OAUTH_CLIENT_SECRET"
    hmpps-domain-events-topic:
      AWS_HMPPS_DOMAIN_EVENTS_ACCESS_KEY: "access_key_id"
      AWS_HMPPS_DOMAIN_EVENTS_SECRET_ACCESS_KEY: "secret_access_key"
      AWS_HMPPS_DOMAIN_EVENTS_TOPIC_ARN: "topic_arn"
    hmpps-tier-offender-events-sqs-instance-output:
      AWS_OFFENDER_EVENTS_ACCESS_KEY: "access_key_id"
      AWS_OFFENDER_EVENTS_SECRET_ACCESS_KEY: "secret_access_key"
      AWS_OFFENDER_EVENTS_QUEUE: "sqs_ptpu_url"
    rds-instance-output:
      DATABASE_USERNAME: "database_username"
      DATABASE_PASSWORD: "database_password"
      DATABASE_ENDPOINT: "rds_instance_endpoint"
      DATABASE_NAME: "database_name"



  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"

generic-prometheus-alerts:
  targetApplication: hmpps-tier
  alertSeverity: hmpps-tier
