generic-service:
  nameOverride: hmpps-tier

  replicaCount: 2
  resources:
    requests:
      cpu: 128m
      memory: 512Mi
    limits:
      cpu: 2048m
      memory: 2Gi

  image:
    repository: quay.io/hmpps/hmpps-tier
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    v1_2_enabled: true
    v0_47_enabled: false
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-tier-cert
    contextColour: green
    path: /
    annotations:
      nginx.ingress.kubernetes.io/custom-http-errors: "418"
      external-dns.alpha.kubernetes.io/aws-weight: "100"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        server_tokens off;
        location /crn/upload {
          deny all;
          return 401;
        }
        location /queue-admin/retry-all-dlqs {
          deny all;
          return 401;
        }

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx1536m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "aws,logstash,stdout"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    HMPPS_SQS_USE_WEB_TOKEN: "true"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]
  namespace_secrets:
    hmpps-tier:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      OAUTH_CLIENT_ID: "OAUTH_CLIENT_ID"
      OAUTH_CLIENT_SECRET: "OAUTH_CLIENT_SECRET"
    rds-instance-output:
      DATABASE_USERNAME: "database_username"
      DATABASE_PASSWORD: "database_password"
      DATABASE_ENDPOINT: "rds_instance_endpoint"
      DATABASE_NAME: "database_name"
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_HMPPSCALCULATIONCOMPLETETOPIC_ARN: "topic_arn"
    hmpps-tier-offender-events-sqs-instance-output:
      HMPPS_SQS_QUEUES_HMPPSOFFENDERQUEUE_QUEUE_NAME: "sqs_ptpu_name"
    hmpps-tier-offender-events-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_HMPPSOFFENDERQUEUE_DLQ_NAME: "sqs_ptpu_name"
    sqs-domain-events-secret:
      HMPPS_SQS_QUEUES_HMPPSDOMAINEVENTSQUEUE_QUEUE_NAME: "sqs_queue_name"
    sqs-domain-events-dl-secret:
      HMPPS_SQS_QUEUES_HMPPSDOMAINEVENTSQUEUE_DLQ_NAME: "sqs_queue_name"

  allowlist:
    groups:
      - internal
      - unilink_staff

  serviceAccountName: hmpps-tier

generic-prometheus-alerts:
  targetApplication: hmpps-tier
  alertSeverity: probation-integration-notifications
