# Per environment values which override defaults in hmpps-tier/values.yaml

generic-service:
  ingress:
    host: hmpps-tier.hmpps.service.justice.gov.uk
  env:
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: https://sign-in.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json
    OAUTH_ENDPOINT_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    ARNS_ENDPOINT_URL: http://hmpps-assess-risks-and-needs.hmpps-assess-risks-and-needs-prod.svc.cluster.local
    HMPPS_TIER_ENDPOINT_URL: https://hmpps-tier.hmpps.service.justice.gov.uk
    TIER_TO_DELIUS_ENDPOINT_URL: http://tier-to-delius.hmpps-probation-integration-services-prod.svc.cluster.local
    TIER_UNSUPERVISED_SUFFIX: "true"
    SENTRY_ENVIRONMENT: prod

  allowlist:
    delius-prod-1: 52.56.115.146/32
    delius-prod-2: 35.178.104.253/32
    delius-prod-3: 35.177.47.45/32

generic-prometheus-alerts:
  sqsOldestAlertQueueNames:
    - "manage-a-workforce-production-hmpps_tier_domain_events_queue"
  sqsNumberAlertQueueNames:
    - "manage-a-workforce-production-hmpps_tier_domain_events_dlq"
  sqsAlertsOldestThreshold: 15
  sqsAlertsTotalMessagesThreshold: 1
  ingress5xxErrorWindowMinutes: 4

full-recalculation:
  schedule: 0 18 * * 5 # Every Friday at 18:00 UTC
  dry-run: false
