---
# Per environment values which override defaults in hmpps-tier/values.yaml

queue_cronjob_schedule: "*/15 * * * *"

generic-service:
  ingress:
    host: hmpps-tier.hmpps.service.justice.gov.uk
  env:
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: https://sign-in.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json
    OAUTH_ENDPOINT_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    ASSESSMENT_ENDPOINT_URL: https://offender-prod.aks-live-1.studio-hosting.service.justice.gov.uk
    HMPPS_TIER_ENDPOINT_URL: https://hmpps-tier.hmpps.service.justice.gov.uk
    TIER_TO_DELIUS_ENDPOINT_URL: https://tier-to-delius.hmpps.service.justice.gov.uk

  allowlist:
    delius-prod-1: "52.56.115.146/32"
    delius-prod-2: "35.178.104.253/32"
    delius-prod-3: "35.177.47.45/32"

  namespace_secrets:
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_HMPPSCALCULATIONCOMPLETETOPIC_ARN: "topic_arn"
    hmpps-tier-offender-events-sqs-instance-output:
      HMPPS_SQS_QUEUES_HMPPSOFFENDERQUEUE_QUEUE_NAME: "sqs_ptpu_name"
    hmpps-tier-offender-events-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_HMPPSOFFENDERQUEUE_DLQ_NAME: "sqs_ptpu_name"
    sqs-domain-events-secret:
      HMPPS_SQS_QUEUES_HMPPSDOMAINEVENTSQUEUE_QUEUE_NAME: "sqs_queue_name"
    sqs-domain-events-dl-secret:
      HMPPS_SQS_QUEUES_HMPPSDOMAINEVENTSQUEUE_DLQ_NAME: "sqs_queue_name"

generic-prometheus-alerts:
  sqsOldestAlertQueueNames:
    - "Digital-Prison-Services-prod-hmpps_tier_offender_events_queue"
    - "manage-a-workforce-production-hmpps_tier_domain_events_queue"
  sqsNumberAlertQueueNames:
    - "Digital-Prison-Services-prod-hmpps_tier_offender_events_queue_dl"
    - "manage-a-workforce-production-hmpps_tier_domain_events_dlq"
  sqsAlertsOldestThreshold: 15
  sqsAlertsTotalMessagesThreshold: 1
  ingress5xxErrorWindowMinutes: 4