# Per environment values which override defaults in hmpps-tier/values.yaml

generic-service:
  ingress:
    host: hmpps-tier-dev.hmpps.service.justice.gov.uk
  env:
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: https://sign-in-dev.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json
    OAUTH_ENDPOINT_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    ARNS_ENDPOINT_URL: https://assess-risks-and-needs-dev.hmpps.service.justice.gov.uk
    HMPPS_TIER_ENDPOINT_URL: https://hmpps-tier-dev.hmpps.service.justice.gov.uk
    TIER_TO_DELIUS_ENDPOINT_URL: https://tier-to-delius-dev.hmpps.service.justice.gov.uk
    TIER_UNSUPERVISED_SUFFIX: "true"
    SENTRY_ENVIRONMENT: dev

  allowlist:
    dxw-vpn: 54.76.254.148/32
    delius-test-1: 35.176.126.163/32
    delius-test-2: 35.178.162.73/32
    delius-test-3: 52.56.195.113/32
  scheduledDowntime:
    enabled: true

full-recalculation:
  schedule: 0 8 * * 1 # Every Monday at 08:00 UTC
  dry-run: false

generic-prometheus-alerts:
  sqsOldestAlertQueueNames:
    - probation-integration-dev-hmpps-tier-events-queue