---
# Per environment values which override defaults in hmpps-tier/values.yaml

queue_cronjob_schedule: "*/15 7-21 * * 1-5"

generic-service:
  ingress:
    host: hmpps-tier-preprod.hmpps.service.justice.gov.uk
  env:
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json
    OAUTH_ENDPOINT_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth/
    ASSESSMENT_ENDPOINT_URL: https://offender-prprod.aks-live-1.studio-hosting.service.justice.gov.uk
    HMPPS_TIER_ENDPOINT_URL: https://hmpps-tier-preprod.hmpps.service.justice.gov.uk
    TIER_TO_DELIUS_ENDPOINT_URL: https://tier-to-delius-preprod.hmpps.service.justice.gov.uk
  allowlist:
    delius-pre-prod-1: "52.56.240.62/32"
    delius-pre-prod-2: "18.130.110.168/32"
    delius-pre-prod-3: "35.178.44.184/32"
  scheduledDowntime:
    enabled: true